name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install pytest and test dependencies
        python -m pip install pytest pytest-cov
        # Install package dependencies
        python -m pip install pydantic boto3
        # Install the package in development mode
        python -m pip install -e .
        
    - name: Test with pytest
      run: |
        python -m pytest --cov=ecs_taskdef tests/
        
    - name: Generate coverage report
      run: |
        python -m pytest --cov=ecs_taskdef --cov-report=xml tests/
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false